<?php
echo "<head>\n"; 
echo "<title>V4U</title>\n"; 
echo "<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\n"; 
echo "<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" />\n"; 
echo "<script type=\"text/javascript\" src=\"js/mootools-release-1.11.js\"></script>\n"; 
echo "<script src=\"js/dropDownMenu.js\" type=\"text/javascript\"></script>\n"; 
echo "<!--[if IE 7]><style>#dropdownMenu li ul ul {margin-left: 100px;}</style><![endif]-->\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "<div id=\"container\">\n"; 
echo "  <div id=\"wrapper\">\n"; 
echo "    <div id=\"top\">\n"; 
echo "      <div class=\"logo\"><a href=\"#\"><span>ICT</span> 4U</a></div>\n"; 
echo "      \n"; 
echo "    </div>\n"; 
echo "    <ul id=\"nav\">\n"; 
echo "      <li class=\"left\">&nbsp;</li>\n"; 
echo "      <li><a class=\"active\" href=\"#\">Home</a></li>\n"; 
echo "      <li> <a href=\"#\">Category <img src=\"images/nav_bullet.jpg\" alt=\"\" /></a>\n"; 
echo "        <ul>\n"; 
echo "          <li><a href=\"Students.html\">Students</a></li>\n"; 
echo "          <li><a href=\"Parents.html\">Parents</a></li>\n"; 
echo "          <li><a href=\"Faculty.html\">Faculty</a></li>\n"; 
echo "          <li><a href=\"Career advisors.html\">Career advisors</a></li>\n"; 
echo "        </ul>\n"; 
echo "      </li>\n"; 
echo "      <li><a href=\"Contact us.html\">Contact Us</a></li>\n"; 
echo "      <li class=\"sep\">&nbsp;</li>\n"; 
echo "      <li class=\"right\">&nbsp;</li>\n"; 
echo "    </ul>\n"; 
echo "    <div id=\"header\">\n"; 
echo "      <div class=\"intro\">\n"; 
echo "        <h2>V4U</h2>\n"; 
echo "        <h3>The number one benefit of information technology is that it empowers people to do what they want to do. It lets people be creative. It lets people be productive. It lets people learn things they didnot think they could learn before, and so in a sense it is all about potential.\n"; 
echo "--STEVE BALLMER</h3>\n"; 
echo "        \n"; 
echo "        <form method=\"get\" id=\"searchform\" action=\"www.google.com.au\">\n"; 
echo "          <div>\n"; 
echo "            <input class=\"searchField\" type=\"text\" value=\"\" name=\"q\" />\n"; 
echo "            <input class=\"searchSubmit\" type=\"submit\" value=\"\" />\n"; 
echo "            <input type=\"hidden\" name=\"sitesearch\" value=\"\" />\n"; 
echo "          </div>\n"; 
echo "        </form>\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div id=\"content\">\n"; 
echo "      <h1>ICT</h1>\n"; 
echo "      <img class=\"alignleft\" src=\"images/temp/post1.jpg\" >\n"; 
echo "      <p><b>Why ICT?</b> Information and Communications Technologies (ICT) education is basically our societies efforts to teach its current and emerging citizens valuable knowledge and skills around computing and communications devices, software that operates them, applications that run on them and systems that are built with them.</p>\n"; 
echo "      <p>ICT is complex and quickly changing, and it is confusing for many people. It is so pervasive in the modern world that everyone has some understanding of it, but those understandings are often wildly divergent.</p>\n"; 
echo "       <a class=\"backToTop\" href=\"#\">&nbsp;</a>\n"; 
echo "      <h1>Global trends</h1>\n"; 
echo "      <img class=\"alignleft\" src=\"images/temp/post2.jpg\" alt=\"\" />\n"; 
echo "      <p>The Australian Computer Society, in a submission to the Commonwealth Government into Australian Technological Innovations notes that 'Compared to other countries,Australia has been spectacularly unsuccessful in producing, commercialising and marketing innovations.Research undertaken by the Australian Government in 2005 found that 85 percent of productivity growth in the manufacturing sector, and up to 78 percent in the services sector, was technology related. This highlights the importance of the ICT industry to the overall productivity of the national economy and its role as a fundamental driver of employment.</p>\n"; 
echo "      \n"; 
echo "      <a class=\"backToTop\" href=\"#\">&nbsp;</a> </div>\n"; 
echo "    <div >\n"; 
echo "      <h2>News & Announcements</h2>\n"; 
echo "      <ul id=\"news\">\n"; 
echo "\n"; 
echo "      \n"; 
echo "          <p>\n"; 
echo "\n"; 
echo "<br />\n"; 
echo "            </p>\n"; 
echo "        </li>\n"; 
echo "        <li> <a href=\"#\"> <img src=\"images/temp/news2.jpg\" alt=\"\" width=\"54\" /> </a>\n"; 
echo "          <h3>News Heading H3</h3>\n"; 
echo "          <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium... <br />\n"; 
echo "            <a href=\"#\">More &raquo;</a></p>\n"; 
echo "        </li>\n"; 
echo "        <li> <a href=\"#\"> <img src=\"images/temp/news3.jpg\" alt=\"\" width=\"54\" /> </a>\n"; 
echo "          <h3>News Heading H3</h3>\n"; 
echo "          <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium... <br />\n"; 
echo "            <a href=\"#\">More &raquo;</a></p>\n"; 
echo "        </li>\n"; 
echo "      </ul>\n"; 
echo "       </div>\n"; 
echo "    <div id=\"footer\">\n"; 
echo "      <div class=\"foot_l\"><a href=\"#\">&nbsp;</a></div>\n"; 
echo "      <div class=\"foot_content\">\n"; 
echo "        <ul>\n"; 
echo "         </ul>\n"; 
echo "        <p>All contents copyright &copy; V4U. All rights reserved.</p>\n"; 
echo "      </div>\n"; 
echo "      <div class=\"foot_r\">&nbsp;</div>\n"; 
echo "      <div class=\"backToTop\"> <a class=\"backToTop\" href=\"#\">&nbsp;</a> </div>\n"; 
echo "      <div class=\"foot_info\">\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "  </div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>
